export default {

  colors: {
    primary:   0x2ECC71,
    success:   0x57F287,
    warning:   0xFEE75C,
    error:     0xED4245,
    info:      0x5DADE2,
    ticket:    0x2ECC71,
    close:     0x99AAB5,
    dark:      0x2C2F33,
    appeal:    0xED4245,
    media:     0xFF73FA,
    report:    0xFEE75C,
    bug:       0xE67E22,
    store:     0xF1C40F,
    support:   0x3498DB,
    critical:  0xFF0000,
  },

  emojis: {
    ticket:    '🎫', lock:       '🔒', unlock:    '🔓',
    add:       '👤', remove:     '❌', claim:     '📌',
    priority:  '⚠️', transcript: '📄', log:       '📋',
    success:   '✅', error:      '❌', warning:   '⚠️',
    loading:   '⏳', info:       'ℹ️', dm:        '📩',
    clock:     '🕐', user:       '👤', staff:     '🛡️',
    ban:       '🔨', mute:       '🔇', media:     '🎥',
    report:    '⚠️', bug:        '🐞', connect:   '🌐',
    store:     '💰', support:    '🛠️', other:     '❓',
    queue:     '⏳', vip:        '⭐', critical:  '🚨',
    exploit:   '💀', gameplay:   '🎮', visual:    '👁️',
    general:   '📦', youtube:    '▶️', tiktok:    '🎵',
    twitch:    '🟣', autoclose:  '⏲️',
  },

  categories: [
    {
      id:          'ban_appeal',
      label:       '🔨 Ban Appeal',
      description: 'Appeal a ban from our server',
      color:       0xED4245,
      pingEnv:     'ROLE_MODERATORS',
      categoryEnv: 'CATEGORY_APPEALS',
      requireRole: 'ROLE_BANNED',
      blockRole:   null,
      rules: [
        '❌ Do **not** lie or submit misleading information.',
        '❌ Do **not** open multiple appeals for the same punishment.',
        '❌ Do **not** DM or ping moderators about your appeal.',
        '✅ Provide your **exact Minecraft username** (case-sensitive).',
        '✅ Be **honest** — admitting fault leads to better outcomes.',
        '✅ Explain clearly **why your ban should be removed**.',
        '✅ First-time appeals are reviewed within **48 hours**.',
        '⚠️ Decisions are **final** — repeated appeals lead to a permanent ban.',
      ],
      closeReasons: [
        { label: '✅ Appeal Accepted — Unbanned',   value: 'unbanned',       description: 'Ban has been lifted' },
        { label: '❌ Appeal Denied',                value: 'denied',         description: 'Appeal was denied' },
        { label: '📝 Denied — Insufficient Reason', value: 'denied_weak',    description: 'Reason was not convincing' },
        { label: '⚖️ Denied — Ban Too Severe',      value: 'denied_severe',  description: 'Offence too serious to appeal' },
        { label: '🔁 Duplicate Appeal',             value: 'duplicate',      description: 'Already appealed this ban' },
        { label: '💤 User Inactive',                value: 'inactive',       description: 'User did not respond' },
        { label: '✏️ Other (type below)',            value: 'other',          description: 'Enter a custom reason' },
      ],
    },
    {
      id:          'mute_appeal',
      label:       '🔇 Mute Appeal',
      description: 'Appeal a mute or chat restriction',
      color:       0xFEE75C,
      pingEnv:     'ROLE_MODERATORS',
      categoryEnv: 'CATEGORY_APPEALS',
      requireRole: 'ROLE_MUTED',
      blockRole:   null,
      rules: [
        '❌ Do **not** submit false information in your appeal.',
        '❌ Do **not** open multiple appeals for the same mute.',
        '✅ Include your **exact Minecraft username**.',
        '✅ Explain what you said and **why it was wrong**.',
        '✅ Provide a strong reason for removing the restriction.',
        '⚠️ Staff decisions are **final**.',
      ],
      closeReasons: [
        { label: '✅ Unmuted',                      value: 'unmuted',        description: 'Mute has been removed' },
        { label: '❌ Denied',                       value: 'denied',         description: 'Appeal denied' },
        { label: '📝 Denied — Weak Reason',         value: 'denied_weak',    description: 'Reason not convincing' },
        { label: '🔁 Duplicate',                    value: 'duplicate',      description: 'Already appealed' },
        { label: '💤 User Inactive',                value: 'inactive',       description: 'No response' },
        { label: '✏️ Other (type below)',            value: 'other',          description: 'Custom reason' },
      ],
    },
    {
      id:          'media_app',
      label:       '🎥 Media Application',
      description: 'Apply for the Media rank',
      color:       0xFF73FA,
      pingEnv:     'ROLE_STAFF',
      categoryEnv: 'CATEGORY_MEDIA',
      requireRole: null,
      blockRole:   'ROLE_MEDIA',
      rules: [
        '❌ Do **not** apply if you already have the Media rank.',
        '❌ Do **not** purchase views, followers or engagement.',
        '❌ Do **not** spam or resubmit after a denial.',
        '✅ You must have **active, consistent content** on your channel.',
        '✅ Your content must be **related to our server** or Minecraft in general.',
        '✅ Minimum requirement: **1,000 subscribers/followers** or **500 avg views**.',
        '✅ Include a **real, active link** to your channel or profile.',
      ],
      closeReasons: [
        { label: '✅ Accepted — Media Rank Granted', value: 'accepted',        description: 'Media rank granted' },
        { label: '❌ Denied — Low Following',        value: 'denied_following',description: 'Does not meet follower minimum' },
        { label: '❌ Denied — Low Views',            value: 'denied_views',    description: 'Average views too low' },
        { label: '❌ Denied — Inactive Channel',     value: 'denied_inactive', description: 'Channel is inactive' },
        { label: '❌ Denied — Unrelated Content',    value: 'denied_content',  description: 'Content not related to server' },
        { label: '🔁 Already Applied',               value: 'already_applied', description: 'Duplicate application' },
        { label: '✏️ Other (type below)',             value: 'other',           description: 'Custom reason' },
      ],
    },
    {
      id:          'player_report',
      label:       '⚠️ Player Report',
      description: 'Report a player for rule-breaking',
      color:       0xFEE75C,
      pingEnv:     'ROLE_MODERATORS',
      categoryEnv: 'CATEGORY_REPORTS',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** submit false or exaggerated reports.',
        '❌ Do **not** use reports to target or harass players.',
        '✅ Provide the **exact Minecraft username** of the player.',
        '✅ Include **evidence** (screenshots, video links).',
        '✅ Reports without evidence may be closed.',
        '✅ Specify the **exact rule** that was broken.',
      ],
      closeReasons: [
        { label: '⚖️ Action Taken',                 value: 'actioned',       description: 'Player was punished' },
        { label: '🔍 Under Review',                  value: 'under_review',   description: 'Being investigated' },
        { label: '❌ Insufficient Evidence',         value: 'no_evidence',    description: 'Not enough proof' },
        { label: '✅ Not a Violation',               value: 'not_violation',  description: 'No rule was broken' },
        { label: '🔁 Already Reported',              value: 'duplicate',      description: 'Already reported' },
        { label: '💤 User Inactive',                 value: 'inactive',       description: 'Reporter did not respond' },
        { label: '✏️ Other (type below)',             value: 'other',          description: 'Custom reason' },
      ],
    },
    {
      id:          'bug_report',
      label:       '🐞 Bug Report',
      description: 'Report a server bug or exploit',
      color:       0xE67E22,
      pingEnv:     'ROLE_DEVELOPERS',
      categoryEnv: 'CATEGORY_BUG',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** abuse or exploit bugs — report them immediately.',
        '❌ Do **not** share exploit details publicly.',
        '❌ Do **not** report the same bug twice.',
        '✅ Describe the bug **step by step** so it can be reproduced.',
        '✅ Include your **IGN**, **server/gamemode** and **date/time**.',
        '✅ Attach **screenshots or a recording** if possible.',
        '⭐ Reporting exploits responsibly may earn you a **reward**.',
      ],
      closeReasons: [
        { label: '🔧 Fixed',                         value: 'fixed',          description: 'Bug has been patched' },
        { label: '📋 Known Bug',                     value: 'known_bug',      description: 'Already tracked' },
        { label: '✅ Not a Bug',                     value: 'not_a_bug',      description: 'Working as intended' },
        { label: '🔁 Duplicate',                     value: 'duplicate',      description: 'Already reported' },
        { label: '🔍 Cannot Reproduce',              value: 'no_repro',       description: 'Unable to reproduce' },
        { label: '🔬 Under Investigation',           value: 'investigating',  description: 'Being looked into' },
        { label: '✏️ Other (type below)',             value: 'other',          description: 'Custom reason' },
      ],
    },
    {
      id:          'connection',
      label:       '🌐 Connection Issues',
      description: 'Trouble connecting to the server',
      color:       0x5DADE2,
      pingEnv:     'ROLE_SUPPORT',
      categoryEnv: 'CATEGORY_SUPPORT',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** open multiple tickets for the same issue.',
        '✅ Describe the **exact error message** you receive.',
        '✅ Confirm you are using the **correct server IP**.',
        '✅ Try the FAQ solutions shown below **before submitting**.',
        '✅ Include your **region/country** and Minecraft version.',
      ],
      closeReasons: [
        { label: '✅ Issue Resolved',                value: 'resolved',       description: 'Connection issue fixed' },
        { label: '🌐 Not a Server Issue',            value: 'not_our_issue',  description: 'Issue is client-side' },
        { label: '💤 User Inactive',                 value: 'inactive',       description: 'No response' },
        { label: '🔁 Duplicate',                     value: 'duplicate',      description: 'Already reported' },
        { label: '✏️ Other (type below)',             value: 'other',          description: 'Custom reason' },
      ],
    },
    {
      id:          'store',
      label:       '💰 Store Support',
      description: 'Rank, purchase or payment issues',
      color:       0xF1C40F,
      pingEnv:     'ROLE_STAFF',
      categoryEnv: 'CATEGORY_STORE',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** share payment card numbers or passwords.',
        '❌ Do **not** open multiple tickets for the same purchase.',
        '✅ Have your **transaction / order ID** ready.',
        '✅ Use the **exact IGN** that was used at checkout.',
        '✅ Attach a **screenshot** of your purchase confirmation.',
        '✅ Refunds are subject to our store **Terms of Service**.',
      ],
      closeReasons: [
        { label: '✅ Issue Resolved',                value: 'resolved',        description: 'Purchase issue resolved' },
        { label: '🎁 Rank / Perk Applied',           value: 'rank_applied',    description: 'Rank or perk has been given' },
        { label: '💸 Refund Issued',                 value: 'refund',          description: 'Refund processed' },
        { label: '❌ Invalid Purchase',              value: 'invalid',         description: 'Purchase could not be verified' },
        { label: '💤 User Inactive',                 value: 'inactive',        description: 'No response' },
        { label: '🔁 Duplicate',                     value: 'duplicate',       description: 'Already submitted' },
        { label: '✏️ Other (type below)',             value: 'other',           description: 'Custom reason' },
      ],
    },
    {
      id:          'general',
      label:       '🛠️ General Support',
      description: 'General gameplay help & questions',
      color:       0x3498DB,
      pingEnv:     'ROLE_SUPPORT',
      categoryEnv: 'CATEGORY_SUPPORT',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** ping or DM staff directly.',
        '❌ Do **not** open multiple tickets for the same issue.',
        '✅ Describe your issue **in as much detail as possible**.',
        '✅ Include your **IGN** and the **gamemode/server** affected.',
        '✅ Mention what you have **already tried** to fix it.',
      ],
      closeReasons: [
        { label: '✅ Issue Resolved',                value: 'resolved',       description: 'Issue fixed' },
        { label: '💤 User Inactive',                 value: 'inactive',       description: 'No response' },
        { label: '🔁 Duplicate',                     value: 'duplicate',      description: 'Already open' },
        { label: '❌ Invalid Request',               value: 'invalid',        description: 'Not a valid support request' },
        { label: '🚪 User Left',                     value: 'user_left',      description: 'User left the server' },
        { label: '✏️ Other (type below)',             value: 'other',          description: 'Custom reason' },
      ],
    },
    {
      id:          'other',
      label:       '❓ Other',
      description: 'Anything that does not fit above',
      color:       0x99AAB5,
      pingEnv:     'ROLE_STAFF',
      categoryEnv: 'CATEGORY_SUPPORT',
      requireRole: null,
      blockRole:   null,
      rules: [
        '❌ Do **not** open a ticket just to chat.',
        '❌ Do **not** ping or DM staff without permission.',
        '✅ Check if your subject fits another category first.',
        '✅ Be **clear and specific** about what you need.',
        '✅ Staff will respond as soon as possible.',
      ],
      closeReasons: [
        { label: '✅ Request Completed',             value: 'completed',      description: 'Fulfilled' },
        { label: '💤 User Inactive',                 value: 'inactive',       description: 'No response' },
        { label: '❌ Invalid Request',               value: 'invalid',        description: 'Not valid' },
        { label: '🚪 User Left',                     value: 'user_left',      description: 'User left' },
        { label: '✏️ Other (type below)',             value: 'other',          description: 'Custom reason' },
      ],
    },
  ],

  priorities: [
    { id: 'low',      label: '🟢 Low',      color: 0x57F287, pingStaff: false },
    { id: 'medium',   label: '🟡 Medium',   color: 0xFEE75C, pingStaff: false },
    { id: 'high',     label: '🔴 High',     color: 0xED4245, pingStaff: true  },
    { id: 'critical', label: '🚨 Critical', color: 0xFF0000, pingStaff: true  },
  ],

  mediaPlatforms: [
    { id: 'youtube', label: '▶️ YouTube',  emoji: '▶️' },
    { id: 'tiktok',  label: '🎵 TikTok',   emoji: '🎵' },
    { id: 'twitch',  label: '🟣 Twitch',   emoji: '🟣' },
  ],

  bugTags: {
    critical:  { pattern: /crash|server down|data.?loss|rollback|critical|unavailable/i, label: '🚨 Critical',  color: 0xFF0000 },
    exploit:   { pattern: /dupe|duplication|x.?ray|xray|hack|cheat|bypass|exploit|abuse/i, label: '💀 Exploit', color: 0x8B0000 },
    gameplay:  { pattern: /pvp|combat|mob|chunk|item|drop|death|kill|enchant|potion|skill/i, label: '🎮 Gameplay', color: 0x2ECC71 },
    visual:    { pattern: /texture|render|display|ui|interface|visual|graphi|invisible|glitch/i, label: '👁️ Visual', color: 0x9B59B6 },
  },

  connectionFaq: [
    {
      emoji: '📊',
      title: 'Check our Status Page',
      fix:   `Visit **${process.env.STATUS_PAGE_URL ?? 'status.yourserver.net'}** to see if the server is online.`,
    },
    {
      emoji: '🔄',
      title: 'Restart Minecraft',
      fix:   'Fully close Minecraft (including the launcher) and reopen it, then try again.',
    },
    {
      emoji: '🌐',
      title: 'Correct Server IP',
      fix:   `Java IP: \`${process.env.SERVER_IP ?? 'play.yourserver.net'}\`\nBedrock IP: \`${process.env.SERVER_IP_BEDROCK ?? 'pe.yourserver.net'}\` (port **19132**)`,
    },
    {
      emoji: '🛡️',
      title: 'Disable VPN / Proxy',
      fix:   'VPNs and proxies are blocked on our network. Disable them and try again.',
    },
    {
      emoji: '🔌',
      title: 'Restart your Router',
      fix:   'Turn your router off, wait 30 seconds, then turn it back on.',
    },
  ],

  limits: {
    maxOpenPerCategory:  1,
    cooldownSeconds:     30,
    minAnswerLength:     15,
    transcriptFolder:    './data/transcripts/',
    autoCloseHours:      48,
    autoCloseCheckMins:  30,
    appealCooldownDays:  7,  
  },
};
